---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - newrelic.newrelic.com
  resources:
  - newrelics
  - nribundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - newrelic.newrelic.com
  resources:
  - newrelics/finalizers
  - nribundles/finalizers
  verbs:
  - update
- apiGroups:
  - newrelic.newrelic.com
  resources:
  - newrelics/status
  - nribundles/status
  verbs:
  - get
  - patch
  - update
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - create
  - list
  - watch
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - create
  - list
  - update
  - patch
  - delete
  - watch
- apiGroups:
  - px.dev
  resources:
  - viziers
  verbs:
  - create
  - get
  - list
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - list
- apiGroups:
  - operators.coreos.com
  resources:
  - operatorgroups
  - catalogsources
  - subscriptions
  - installplans
  verbs:
  - get
  - list
  - create
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - get
  - create
  - list
  - delete
  - update
  - patch
  - watch
##
## Rules for charts.newrelic.com/v1alpha1, Kind: NewRelic
##
- apiGroups:
  - charts.newrelic.com
  resources:
  - newrelics
  - newrelics/status
  - newrelics/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  - apps
  - rbac.authorization.k8s.io
  - extensions
  - etcd.database.coreos.com
  - batch
  - nats.io
  - policy
  - apiextensions.k8s.io
  - px.dev
  resources:
  - clusterroles
  - clusterrolebindings
  - configmaps
  - customresourcedefinitions
  - secrets
  - pods
  - events
  - services
  - deployments
  - daemonsets
  - nodes
  - persistentvolumes
  - persistentvolumeclaims
  - roles
  - rolebindings
  - serviceaccounts
  - etcdclusters
  - statefulsets
  - cronjobs
  - jobs
  - natsclusters
  - poddisruptionbudgets
  - viziers
  - viziers/status
  - podsecuritypolicies
  verbs: ["*"]
# Allow read-only access to storage class.
- apiGroups:
  - storage.k8s.io
  - ""
  resources:
  - storageclasses
  - namespaces
  verbs: ["get", "list"]

