apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: newrelic-k8s-operator
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: newrelic-k8s-operator
  name: newrelic-k8s-operator-controller-manager
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: newrelic-k8s-operator
    app.kubernetes.io/instance: leader-election-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: role
    app.kubernetes.io/part-of: newrelic-k8s-operator
  name: newrelic-k8s-operator-leader-election-role
  namespace: {{.Release.Namespace}}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: newrelic-k8s-operator-manager-role
rules:
- apiGroups:
  - newrelic.com
  resources:
  - monitors
  - nribundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - newrelic.com
  resources:
  - monitors/finalizers
  - nribundles/finalizers
  verbs:
  - update
- apiGroups:
  - newrelic.com
  resources:
  - monitors/status
  - nribundles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - create
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - create
  - list
  - update
  - patch
  - delete
  - watch
- apiGroups:
  - px.dev
  resources:
  - viziers
  verbs:
  - create
  - get
  - list
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - list
- apiGroups:
  - operators.coreos.com
  resources:
  - operatorgroups
  - catalogsources
  - subscriptions
  - installplans
  verbs:
  - get
  - list
  - create
  - watch
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - get
  - create
  - list
  - delete
  - update
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  - apps
  - rbac.authorization.k8s.io
  - extensions
  - etcd.database.coreos.com
  - batch
  - nats.io
  - policy
  - apiextensions.k8s.io
  - px.dev
  resources:
  - clusterroles
  - clusterrolebindings
  - configmaps
  - customresourcedefinitions
  - secrets
  - pods
  - events
  - services
  - deployments
  - daemonsets
  - nodes
  - persistentvolumes
  - persistentvolumeclaims
  - roles
  - rolebindings
  - serviceaccounts
  - etcdclusters
  - statefulsets
  - cronjobs
  - jobs
  - natsclusters
  - poddisruptionbudgets
  - viziers
  - viziers/status
  - podsecuritypolicies
  verbs:
  - '*'
- apiGroups:
  - storage.k8s.io
  - ""
  resources:
  - storageclasses
  - namespaces
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: newrelic-k8s-operator-metrics-auth-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: newrelic-k8s-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: newrelic-k8s-operator
    app.kubernetes.io/instance: newrelic-editor-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: newrelic-k8s-operator
  name: newrelic-k8s-operator-newrelic-editor-role
rules:
- apiGroups:
  - newrelic.com
  resources:
  - monitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - newrelic.com
  resources:
  - monitors/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: newrelic-k8s-operator
    app.kubernetes.io/instance: newrelic-viewer-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: newrelic-k8s-operator
  name: newrelic-k8s-operator-newrelic-viewer-role
rules:
- apiGroups:
  - newrelic.com
  resources:
  - monitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - newrelic.com
  resources:
  - monitors/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: newrelic-k8s-operator
    app.kubernetes.io/instance: nribundle-editor-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: newrelic-k8s-operator
  name: newrelic-k8s-operator-nribundle-editor-role
rules:
- apiGroups:
  - newrelic.com
  resources:
  - nribundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - newrelic.com
  resources:
  - nribundles/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: newrelic-k8s-operator
    app.kubernetes.io/instance: nribundle-viewer-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: newrelic-k8s-operator
  name: newrelic-k8s-operator-nribundle-viewer-role
rules:
- apiGroups:
  - newrelic.com
  resources:
  - nribundles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - newrelic.com
  resources:
  - nribundles/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: newrelic-k8s-operator
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: newrelic-k8s-operator
  name: newrelic-k8s-operator-leader-election-rolebinding
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: newrelic-k8s-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: newrelic-k8s-operator-controller-manager
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: newrelic-k8s-operator
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: newrelic-k8s-operator
  name: newrelic-k8s-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: newrelic-k8s-operator-manager-role
subjects:
- kind: ServiceAccount
  name: newrelic-k8s-operator-controller-manager
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: newrelic-k8s-operator-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: newrelic-k8s-operator-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: newrelic-k8s-operator-controller-manager
  namespace: {{.Release.Namespace}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: newrelic-k8s-operator
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: newrelic-k8s-operator
    control-plane: controller-manager
  name: newrelic-k8s-operator-controller-manager
  namespace: {{.Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --leader-elect
        - --leader-election-id=newrelic-k8s-operator
        image: {{ include "newrelic-k8s-operator.images.operator.image" . }}
        imagePullPolicy: {{ .Values.images.operator.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: newrelic-k8s-operator-controller-manager
      {{- if .Values.images.pullSecrets }}
      imagePullSecrets: {{ toYaml .Values.images.pullSecrets | nindent 6 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
