apiVersion: v1
kind: Secret
metadata:
    name: newrelic-secrets
    namespace: {{.Release.Namespace}}
type: Opaque
stringData:
{{ if .Values.global.licenseKey }}
    license-key: {{ .Values.global.licenseKey }}
{{- end }}
{{ if and .Values.newRelicLicenseKey (not .Values.global.licenseKey) }}
    license-key: {{.Values.newRelicLicenseKey}}
{{- end}}
