{{if .Values.newRelicLicenseKey}}
apiVersion: v1
kind: Secret
metadata:
    name: newrelic-secrets
    namespace: {{.Release.Namespace}} 
type: Opaque
stringData:
    license-key: {{.Values.newRelicLicenseKey}}
{{- end}}
